// Top-level build file
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// ADB 辅助功能绕过模块：可通过命令行参数 -PenableAdbBypass=true 开启
ext {
    enableAdbBypass = project.hasProperty('enableAdbBypass') ? project.getProperty('enableAdbBypass').toBoolean() : false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
